version: '3.9'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:

  postgres:
    image: postgres:14-alpine
    container_name: inMotion_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  minio:
    image: bitnami/minio:latest
    container_name: inMotion_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=inMotionMinioUser
      - MINIO_ROOT_PASSWORD=inMotionSecretPassword
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: inMotion_rabbitmq
    ports:    
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

  # DOTNET packages
  imsauth:
    build:
      context: ./in-motion-server/
      dockerfile: ./Auth/development.Dockerfile
    container_name: inMotion_imsAuth
    ports:
      - "801:80"
      - "4431:443"
    networks:
      - backend
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
  
  imsemail:
    build:
      context: ./in-motion-server/
      dockerfile: ./Email/development.Dockerfile
    container_name: inMotion_imsEmail
    ports:
      - "802:80"
      - "4432:443"
    networks:
      - backend
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      
  imsfriends:
    build:
      context: ./in-motion-server/
      dockerfile: ./Friends/development.Dockerfile
    container_name: inMotion_imsFriends
    ports:
      - "803:80"
      - "4433:443"
    networks:
      - backend
    links:
      - rabbitmq
      - postgres
    depends_on:
       - rabbitmq
       - postgres