// <auto-generated />
using System;
using IMS.Shared.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMS.Shared.Domain.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20230501154644_Init migration")]
    partial class Initmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Other.Localization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("localization", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Other.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 740, DateTimeKind.Utc).AddTicks(3060))
                        .HasColumnName("creation_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("FrontVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("front_video_id");

                    b.Property<Guid>("LocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("localization_id");

                    b.Property<Guid>("RearVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("rear_video_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("FrontVideoId")
                        .IsUnique();

                    b.HasIndex("LocalizationId");

                    b.HasIndex("RearVideoId")
                        .IsUnique();

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 755, DateTimeKind.Utc).AddTicks(6610))
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 755, DateTimeKind.Utc).AddTicks(6930))
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("post_comment", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.PostVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 755, DateTimeKind.Utc).AddTicks(4980))
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastEditionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 755, DateTimeKind.Utc).AddTicks(5350))
                        .HasColumnName("last_edition_name");

                    b.Property<Guid>("PostFrontId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_front_id");

                    b.Property<Guid>("PostRearId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_rear_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("post_videos", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_key");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProfileVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_video_id");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProfileVideoId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.UserProfileVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 740, DateTimeKind.Utc).AddTicks(1500))
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastEditionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 15, 46, 44, 740, DateTimeKind.Utc).AddTicks(1900))
                        .HasColumnName("last_edition_name");

                    b.HasKey("Id");

                    b.ToTable("user_profile_video", (string)null);
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("PostId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Other.Tag", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.Post", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Shared.Domain.Entities.Post.PostVideo", "FrontVideo")
                        .WithOne("PostFront")
                        .HasForeignKey("IMS.Shared.Domain.Entities.Post.Post", "FrontVideoId")
                        .HasPrincipalKey("IMS.Shared.Domain.Entities.Post.PostVideo", "PostFrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Shared.Domain.Entities.Other.Localization", "Localization")
                        .WithMany()
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Shared.Domain.Entities.Post.PostVideo", "RearVideo")
                        .WithOne("PostRear")
                        .HasForeignKey("IMS.Shared.Domain.Entities.Post.Post", "RearVideoId")
                        .HasPrincipalKey("IMS.Shared.Domain.Entities.Post.PostVideo", "PostRearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("FrontVideo");

                    b.Navigation("Localization");

                    b.Navigation("RearVideo");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.PostComment", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Shared.Domain.Entities.Post.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.PostVideo", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.Provider", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.User", "User")
                        .WithMany("Providers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.User", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.User.UserProfileVideo", "ProfileVideo")
                        .WithOne("Author")
                        .HasForeignKey("IMS.Shared.Domain.Entities.User.User", "ProfileVideoId")
                        .HasPrincipalKey("IMS.Shared.Domain.Entities.User.UserProfileVideo", "AuthrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileVideo");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("IMS.Shared.Domain.Entities.Post.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Shared.Domain.Entities.Other.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.Post", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.Post.PostVideo", b =>
                {
                    b.Navigation("PostFront");

                    b.Navigation("PostRear");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.User", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("IMS.Shared.Domain.Entities.User.UserProfileVideo", b =>
                {
                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
