spring:
  application:
    name: "inMotion media service"
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    active: docker

server:
  tomcat:
    max-http-form-post-size: 50MB

springdoc:
  swagger-ui:
    path: "/api/documentation"
