spring:
  application:
    name: "inMotion media service"
  output:
    ansi:
      enabled: always

minio:
  bucket:
    name: cinehub
  access:
    key: root
    secret: password
  url: http://localhost:9000

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB


