spring:
  application:
    name: "inMotion media service"
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB

minio:
  buckets:
    profile_videos: in-motion-profile-videos
    posts: in-motion-posts
  access:
    key: inMotionMinioUser
    secret: inMotionSecretPassword
  url: http://localhost:9000


