spring:
  application:
    name: "inMotion media service"
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    active: dev





